project:
  type: website

execute:
  freeze: auto

website:
  title: "SCC243 Sustainable Computing Labs"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - week1/git_repo_setup.md
      - week1/week1-task.md
      - week2/week2-task.md
      - week3/week3-task.md
      # - week4/week4-task.md
      # - week5/week5-task.md
      # - week6/week6-task.md
      # - week7/week7-task.md
      # - week8/week8-task.md
      # - week9/week9-task.md
      # - week10/week10-task.md

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    html-math-method: mathml
